export type LeadStatus = 'new' | 'contacted' | 'paid' | 'lost';
export type IntentLevel = 'low' | 'medium' | 'high';
export type InputMethod = 'manual' | 'paste' | 'voice';

export interface Lead {
  id: string;
  user_id: string;
  full_name: string;
  phone: string | null;
  item_of_interest: string | null;
  amount: number | null;
  status: LeadStatus;
  intent_level: IntentLevel;
  input_method: InputMethod;
  raw_paste_text: string | null;
  raw_voice_url: string | null;
  last_contacted_at: string | null;
  follow_up_due_at: string | null;
  alert_sent: boolean;
  notes: string | null;
  whatsapp_url: string | null; // Generated by DB
  created_at: string;
  updated_at: string;
}