import { useState, useEffect, useCallback } from "react";
import { createClient } from "@/lib/supabase/client";
import { Debt } from "@/types/debt";

export function useDebts() {
  const [debts, setDebts] = useState<Debt[]>([]);
  const [loading, setLoading] = useState(true);
  const supabase = createClient();

  const fetchDebts = useCallback(async () => {
    const { data, error } = await supabase
      .from("debts")
      .select("*")
      .order("created_at", { ascending: true });
    
    if (!error && data) {
      setDebts(data as Debt[]);
    }
    setLoading(false);
  }, [supabase]);

  useEffect(() => {
    fetchDebts();
    
    const channel = supabase
      .channel("debts-realtime")
      .on(
        "postgres_changes", 
        { event: "*", schema: "public", table: "debts" }, 
        () => fetchDebts()
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [fetchDebts, supabase]);

  const settleDebt = async (debt: Debt) => {
    try {
      const { error: debtError } = await supabase
        .from("debts")
        .update({
          is_settled: true,
          amount_paid: debt.total_amount,
          // balance is generated by the DB, do not include it here
          updated_at: new Date().toISOString()
        })
        .eq("id", debt.id);

      if (debtError) throw debtError;

      if (debt.sale_id) {
        await supabase
          .from("sales")
          .update({
            amount_paid: debt.total_amount,
            payment_status: "paid",
          })
          .eq("id", debt.sale_id);
      }

      await fetchDebts();
      alert(`${debt.customer_name}'s debt has been cleared!`);

    } catch (err: any) {
      console.error("Settlement Error:", err);
      alert("Failed to settle: " + err.message);
    }
  };

  return { debts, loading, settleDebt, refresh: fetchDebts };
}